services:
  postgres:
    image: postgres:latest
    container_name: multi_bank_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: multi_bank
    ports:
      - "5423:5432"
    volumes:
      - type: bind
        source: e:/psgdata
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d multi_bank"]
      interval: 5s
      timeout: 5s
      retries: 5

